lyceum/about/urls.py
from django.urls import path
from . import views
app_name = 'about'
urlpatterns = [
    path('', views.description,  name='description'),
    path('feedback_form/', views.feedback_form, name='feedback_form'),
]

lyceum/lyceum/urls.py
import django.conf
from django.conf.urls.static import static
# from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings
urlpatterns = [
    path('', include('homepage.urls')),
    path('catalog/', include('catalog.urls')),
    path('about/', include('about.urls')),
    path('admin/', admin.site.urls),
    path('download/', include('download.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
# добавим медиа файлы в django
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lyceum/about/forms.py
from django import forms


class FeedbackForm(forms.Form):
    name = forms.CharField(
        label='Name',
        max_length=100,
        # validators=[start_with_a],
    )
    email = forms.EmailField(
        label='Mail',
        max_length=100,
    )

lyceum/about/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import FeedbackForm

from django.core.mail import send_mail
# Create your views here.
def description(request):
    template = 'about/description.html'
    context = {}
    return render(request, template, context)


def feedback_form(request):
    template = 'about/form_application.html'
    feedback_form = FeedbackForm()
    context = {
        'feedback_form': feedback_form,
    }
    if request.method == 'POST' and feedback_form.is_valid():
        name = request.POST.get('name')
        send_mail(
            'Subject here',
            name,
            'from@example.com',
            ['to@example.com'],
            fail_silently=False,
        )
        return redirect('catalog:item_list')
    return render(request, template, context)

lyceum/templates/about/description.html
{% extends "base.html" %}
{% block title %} About {% endblock %}
{% block content %}
    <div class="container">
        <h2 class="text-center">
            О проекте
        </h2>
        <h4 class="text-center">
            <a href="{% url 'about:feedback_form' %}">Feedback Form</a>
        </h4>
    </div>
{% endblock %}

lyceum/templates/about/form_application.html
{% extends "base.html" %}
{% block title %} Feedback form {% endblock %}
{% block content %}
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <ul>
            {{ feedback_form.as_p }}
        </ul>
        <input type="submit" value="Submit">
    </form>
{% endblock %}