lyceum/about/urls.py
from django.urls import path
from . import views
app_name = 'about'
urlpatterns = [
    path('', views.description,  name='description'),
    path('feedback_form/', views.feedback_form, name='feedback_form'),
]

lyceum/catalog/urls.py
import django.urls
from django.urls import path, re_path
from . import views
from . import converters
app_name = 'catalog'

django.urls.register_converter(
    converters.PositiveIntegerConverter,
    'positive',
)
urlpatterns = [
    path('', views.item_list, name='item_list'),
    path('<int:element>/', views.item_detail, name='item_detail'),
    # path('converter/<positive:element>/', views.item_detail),
    # re_path(r'^re/(?P<element>[1-9]\d*)/$', views.item_detail),
]

lyceum/homepage/urls.py
from django.urls import path
from . import views
app_name = 'homepage'
urlpatterns = [
    path('', views.home, name='homepage_main'),
    path('coffee/', views.coffee, name='homepage_coffeepoint'),
]

lyceum/lyceum/urls.py
import django.conf
from django.conf.urls.static import static
# from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings
urlpatterns = [
    path('', include('homepage.urls')),
    path('catalog/', include('catalog.urls')),
    path('about/', include('about.urls')),
    path('admin/', admin.site.urls),
    path('download/', include('download.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
# добавим медиа файлы в django
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lyceum/templates/includes/footer.html
<footer>
  <div class="container">
  {% load static %}
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <span class="mb-3 mb-md-0 text-body-secondary">© 2024 Company, Inc</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
      <li class="ms-3"><a class="text-body-secondary" href="https://vk.com/crustaceano" target="_blank"><img class="bi me-4" src="{% static 'img/vk_logo.png' %}" width="50" height="50"></a></li>
      <li class="ms-3"><a class="text-body-secondary" href="https://t.me/omar_panda" target="_blank"><img class="bi me-4" src="{% static 'img/telegram_logo.png' %}" width="50" height="50"></a></li>
    </ul>
  </footer>
  </div>
</footer>

lyceum/templates/includes/header.html
<header>
  {% load static %}
  <div class="container">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <img class="bi me-4" src="{% static 'img/panda-bear.png'%}" width="50" height="50">
        <span class="fs-4">My shop project</span>
      </a>
      {% with url_name=request.resolver_match.url_name %}
      <ul class="nav nav-pills">
        {% if request.user and request.user.is_superuser %}
        <li class="nav-item"><a href="{% url 'admin:index' %}" class="nav-link">Admin</a></li>
        {% endif %}
        <li class="nav-item"><a href="{% url 'homepage:homepage_main' %}" class="nav-link {% if url_name == 'homepage_main' %}active{% endif %}" aria-current="page">Home</a></li>
        <li class="nav-item"><a href="{% url 'about:description' %}" class="nav-link {% if url_name == 'description' %}active{% endif %}">About</a></li>
        <li class="nav-item"><a href="{% url 'catalog:item_list' %}" class="nav-link {% if url_name == 'item_list' %}active{% endif %}">Item list</a></li>
      </ul>
      {% endwith %}
    </header>
  </div>
</header>